root = "./"
testdata_dir = "testdata"

[build]
  args_bin = ["serve"]
  bin = "main.exe"
  cmd = "go build -o ./main.exe ./ && templ generate --notify-proxy"
  delay = 200
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "html", "css", "env"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = true
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = true
  rerun_delay = 700
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = true

[proxy]
  enabled = false
  app_port = 8080
  proxy_port = 3000

[screen]
  clear_on_rebuild = false
  keep_scroll = true
